---
- name: Download Podman Image
  hosts: all

  tasks:
  - name: Pull image from registry
    containers.podman.podman_image:
      name: rockylinux:9  # Replace with the image name (e.g., nginx)
      state: present

